37 implement sphinx for docs
simonsobs/SOLikeT pull request #100
Opened 2023-02-27 12:23 UTC by HTJense

This should:

- Add a docs target in tox.
- Add a workflow such that docs are built whenever the `master` branch gets pushed or a PR gets merged.

It should also be setup for readthedocs, but I am not 100% sure if it works correctly.

2023-02-27 12:44 UTC, HTJense commented
Current state passes Documentation checks (see [here](https://github.com/simonsobs/SOLikeT/actions/runs/4282445705/jobs/7456730996)).

2023-02-27 16:59 UTC, HTJense commented
This seems to be setup fine now (see [the current docs](https://soliket.readthedocs.io/en/latest/index.html)).
One (optional) improvement we can consider is to use autodoc's feature to [fake imports](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports) so that pyCCL (and others) installation can be skipped for speed and stability issues.

2023-02-28 10:45 UTC, itrharrison requested changes

2023-02-28 10:45 UTC, itrharrison commented on README.rst
> +For a set of detailed instructions for different machines (e.g. NERSC), please see `here<INSTALL.rst>`_.
Link formatting problem.

2023-02-28 11:15 UTC, HTJense commented on README.rst
> +For a set of detailed instructions for different machines (e.g. NERSC), please see `here<INSTALL.rst>`_.
Fixed.

2023-02-28 13:31 UTC, itrharrison approved these changes
LGTM!

2023-02-28 13:31 UTC, merged