Make code and test compatible with new version of mflike and Cobaya
simonsobs/SOLikeT pull request #23
Opened 2021-09-20 16:39 UTC by paganol

This PR addresses issue #20 and other incompatibilities:
- We updated mflike to the new version, which includes a bunch of new nuisance parameters
- We fixed the test for mflike 
- We fixed the compatibility of cobaya to version 3.1.1

2021-09-25 14:58 UTC, itrharrison requested changes
This looks good in both fixing the bugs with fgspectra installation, and with the `cobaya.conventions` in the new cobaya version, as well as doing some work with the new mflike.

Possibly in future it would be better to do the bug fixes as separate PRs which go in before the new functionality with mflike, but should not be a big problem for here as I don't think there is any conflicting work done elsewhere, apart from Jack's PR, but I think that can be superseded without too much wasted effort.

2021-09-25 14:58 UTC, itrharrison commented on soliket/mflike.py
> +                              _packages_path)
`_packages_path` is no longer set, so this may fail. Is it defined elsewhere?

2021-09-25 14:58 UTC, itrharrison commented on soliket/lensing/lensing.py
> -from cobaya.conventions import _packages_path
`_packages_path` is no longer set, and appears on l48 so this may fail. Is it defined elsewhere?

2021-09-28 15:26 UTC, paganol commented
Hi @itrharrison the last push should solve the issue you mentioned

2021-09-28 16:23 UTC, itrharrison approved these changes

2021-09-28 17:43 UTC, merged